<?php
/**
 * This file is automatically generated by the install process.
 * Please do not alter it manually!
 * DATE GENERATED: 2014-10-26 11:10:19
 */
define('MYSQL_HOST', 'localhost');
define('MYSQL_USERNAME', 'root');
define('MYSQL_PASSWORD', 'rootpass02');
define('MYSQL_PORT', '3306');
define('DATABASE_NAME', 'devicemanagement');
define('USERS_TABLE', 'users');
define('SESSIONS_TABLE', 'sessions');
define('BOOKINGS_TABLE', 'bookings');
define('PORTALS_TABLE', 'portals');
define('COOKIE_NAME', 'axis-home');
?>
