<?php
class ConfigFile {
/**
 * This file is automatically generated by the instal/setup process.
 * Please do not alter it manually!
 * DATE GENERATED: 2014-10-20 16:10:18
 */
public $mysql_host = "localhost";
public $mysql_username = "root";
public $mysql_password = "admin";
public $mysql_port = "3306";
public $database_name = "devicemanagement";
public $users_table = "users";
public $sessions_table = "sessions";
public $bookings_table = "bookings";
public $portals_table = "portals";
public $cookie_name = "axis-home";
}
?>